apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: 1-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 1-component
    app.kubernetes.io/part-of: purple-mermaid-app
  name: 1-component
  namespace: beaumorley
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: 1-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: 1-component
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
            -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
            -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
            -Duser.home=/home/jboss
        - name: MAVEN_OPTS
          value: $(JAVA_OPTS)
        - name: SPRING_PROFILES_ACTIVE
          value: mysql
        - name: MYSQL_URL
          value: jdbc:mysql://mysql-workspace:3306/petclinic
        image: quay.io/redhat-appstudio/user-workload:beaumorley-1-component
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: "1"
            memory: 768Mi
status: {}
